/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package comandados;

import model.Comanda;

/**
 *
 * @author gabri
 */
public class NovoPedido extends javax.swing.JFrame {

    /**
     * Creates new form NovoPedido
     */
    public NovoPedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloJL = new javax.swing.JLabel();
        daCasaJL = new javax.swing.JLabel();
        tipoJL = new javax.swing.JLabel();
        burguerJL = new javax.swing.JLabel();
        kidsJL = new javax.swing.JLabel();
        baconJL = new javax.swing.JLabel();
        cheddarJL = new javax.swing.JLabel();
        qtdDaCasaJTF = new javax.swing.JTextField();
        quantidadeJL = new javax.swing.JLabel();
        qtdBuerguerJTF = new javax.swing.JTextField();
        qtdKidsJTF = new javax.swing.JTextField();
        qtdBaconJTF = new javax.swing.JTextField();
        qtdCheddarJTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        aguaGasJL = new javax.swing.JLabel();
        aguaJL = new javax.swing.JLabel();
        cocaColaJL = new javax.swing.JLabel();
        qtdAguaGasJTF = new javax.swing.JTextField();
        qtdAguaJTF = new javax.swing.JTextField();
        qtdCocaColaJTF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tituloJL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tituloJL.setText("Faça o pedido!");

        daCasaJL.setText("da Casa:");

        tipoJL.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        tipoJL.setText("Hamburguers");

        burguerJL.setText("Burguer:");

        kidsJL.setText("Kids:");

        baconJL.setText("Bacon:");

        cheddarJL.setText("Cheddar:");

        qtdDaCasaJTF.setText("0");

        quantidadeJL.setText("Quantidade");

        qtdBuerguerJTF.setText("0");

        qtdKidsJTF.setText("0");

        qtdBaconJTF.setText("0");

        qtdCheddarJTF.setText("0");

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel1.setText("Bedidas");

        aguaGasJL.setText("Água c/ gás:");

        aguaJL.setText("Água");

        cocaColaJL.setText("Coca-Cola");

        qtdAguaGasJTF.setText("0");

        qtdAguaJTF.setText("0");

        qtdCocaColaJTF.setText("0");

        jButton1.setText("Efetuar pedido");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cocaColaJL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(qtdCocaColaJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(aguaJL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(qtdAguaJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(aguaGasJL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(qtdAguaGasJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(cheddarJL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(qtdCheddarJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(baconJL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(qtdBaconJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(burguerJL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(qtdBuerguerJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(daCasaJL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(qtdDaCasaJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(tituloJL)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tipoJL)
                                        .addGap(243, 243, 243)
                                        .addComponent(quantidadeJL))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(kidsJL)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(qtdKidsJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(41, 41, 41))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloJL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoJL)
                    .addComponent(quantidadeJL))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(daCasaJL)
                    .addComponent(qtdDaCasaJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(burguerJL)
                    .addComponent(qtdBuerguerJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kidsJL)
                    .addComponent(qtdKidsJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(baconJL)
                    .addComponent(qtdBaconJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cheddarJL)
                    .addComponent(qtdCheddarJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aguaGasJL)
                    .addComponent(qtdAguaGasJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aguaJL)
                    .addComponent(qtdAguaJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cocaColaJL)
                    .addComponent(qtdCocaColaJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        Comanda comanda = new Comanda();
        if(!qtdDaCasaJTF.getText().equals("0")){
            comanda.setDaCasa(qtdDaCasaJTF.getText());
        } else{
            comanda.setDaCasa("0");
        }
        if(!qtdBuerguerJTF.getText().equals("0")){
            comanda.setBurguer(qtdBuerguerJTF.getText());
        } else{
            comanda.setBurguer("0");
        }
        if(!qtdKidsJTF.getText().equals("0")){
            comanda.setKids(qtdKidsJTF.getText());
        } else{
            comanda.setKids("0");
        }
        if(!qtdBaconJTF.getText().equals("0")){
            comanda.setBacon(qtdBaconJTF.getText());
        } else{
            comanda.setBacon("0");
        }
        if(!qtdCheddarJTF.getText().equals("0")){
            comanda.setCheddar(qtdCheddarJTF.getText());
        } else{
            comanda.setCheddar("0");
        }
        if(!qtdAguaGasJTF.getText().equals("0")){
            comanda.setAguaGas(qtdAguaGasJTF.getText());
        } else{
            comanda.setAguaGas("0");
        }
        if(!qtdAguaJTF.getText().equals("0")){
            comanda.setAgua(qtdAguaJTF.getText());
        } else{
            comanda.setAgua("0");
        }
        if(!qtdCocaColaJTF.getText().equals("0")){
            comanda.setCocaCola(qtdCocaColaJTF.getText());
        } else{
            comanda.setCocaCola("0");
        }
               
        comanda.setId(Principal.numeroComanda);
        Comandados.comandas.add(comanda);
        Principal.numeroComanda += 1;
        dispose();
   
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovoPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aguaGasJL;
    private javax.swing.JLabel aguaJL;
    private javax.swing.JLabel baconJL;
    private javax.swing.JLabel burguerJL;
    private javax.swing.JLabel cheddarJL;
    private javax.swing.JLabel cocaColaJL;
    private javax.swing.JLabel daCasaJL;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel kidsJL;
    private javax.swing.JTextField qtdAguaGasJTF;
    private javax.swing.JTextField qtdAguaJTF;
    private javax.swing.JTextField qtdBaconJTF;
    private javax.swing.JTextField qtdBuerguerJTF;
    private javax.swing.JTextField qtdCheddarJTF;
    private javax.swing.JTextField qtdCocaColaJTF;
    private javax.swing.JTextField qtdDaCasaJTF;
    private javax.swing.JTextField qtdKidsJTF;
    private javax.swing.JLabel quantidadeJL;
    private javax.swing.JLabel tipoJL;
    private javax.swing.JLabel tituloJL;
    // End of variables declaration//GEN-END:variables
}
